-- EPT-Kompass — initial schema, v2 (free tier, no AI dependency)
-- Run with: supabase db push
--
-- Design notes:
-- * Content tables (tracks, modules, chapters, lessons, formulas, glossary_terms, exercises)
--   are READ by any authenticated user and WRITTEN only by the seed script / service role.
-- * Per-user tables (user_progress, exercise_attempts, srs_cards, study_plan, past_exams,
--   past_exam_questions) are readable and writable ONLY by the owning user.
-- * Every exercise stores its full pedagogical payload in `payload` (jsonb):
--   correct answer, hint, solution_mdx, common_mistakes array, discussion_mdx.
--   No AI is needed at runtime — everything the student reads is pre-authored.
-- * All tables use uuid primary keys generated by gen_random_uuid().
-- * Timestamps are `timestamptz` and default to now() so the client never has to set them.

begin;

create extension if not exists "pgcrypto";
create extension if not exists pg_trgm;

----------------------------------------------------------------------
-- 1. PROFILES
----------------------------------------------------------------------

create table public.profiles (
  id                      uuid primary key references auth.users(id) on delete cascade,
  full_name               text,
  target_graduation_date  date,
  current_semester        smallint check (current_semester between 1 and 12),
  german_level            text check (german_level in ('A1','A2','B1','B2','C1','C2')),
  ui_language             text not null default 'en' check (ui_language in ('de','en')),
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

----------------------------------------------------------------------
-- 2. CONTENT TREE — tracks → modules → chapters → lessons
----------------------------------------------------------------------

create table public.tracks (
  id             uuid primary key default gen_random_uuid(),
  code           text unique not null,              -- '0', 'A', 'B', 'C', 'D'
  name_de        text not null,
  name_en        text not null,
  description_en text,
  position       smallint not null,
  created_at     timestamptz not null default now()
);

create table public.modules (
  id             uuid primary key default gen_random_uuid(),
  track_id       uuid not null references public.tracks(id) on delete cascade,
  code           text unique not null,              -- 'thermodynamik-1'
  name_de        text not null,
  name_en        text not null,
  semester       smallint,                          -- 1..6, null for Track 0
  ects           smallint,
  position       smallint not null,
  description_en text,
  created_at     timestamptz not null default now()
);

create table public.chapters (
  id         uuid primary key default gen_random_uuid(),
  module_id  uuid not null references public.modules(id) on delete cascade,
  code       text not null,
  name_de    text not null,
  name_en    text not null,
  position   smallint not null,
  unique (module_id, code)
);

create table public.lessons (
  id                uuid primary key default gen_random_uuid(),
  chapter_id        uuid not null references public.chapters(id) on delete cascade,
  slug              text not null,
  name_de           text not null,
  name_en           text not null,
  position          smallint not null,
  body_mdx          text,                           -- full MDX source
  estimated_minutes smallint,
  prerequisites     jsonb not null default '[]'::jsonb,  -- array of lesson_id strings
  status            text not null default 'stub' check (status in ('stub','draft','published')),
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (chapter_id, slug)
);

create index lessons_chapter_position_idx on public.lessons(chapter_id, position);
create index lessons_status_idx on public.lessons(status);

----------------------------------------------------------------------
-- 3. FORMULAS & GLOSSARY
----------------------------------------------------------------------

create table public.formulas (
  id             uuid primary key default gen_random_uuid(),
  lesson_id      uuid references public.lessons(id) on delete set null,
  module_id      uuid references public.modules(id) on delete set null,
  name_de        text not null,
  name_en        text not null,
  latex          text not null,
  variables      jsonb not null default '[]'::jsonb,   -- [{symbol, name_de, name_en, unit}]
  description_en text,
  created_at     timestamptz not null default now()
);

create index formulas_module_idx on public.formulas(module_id);
create index formulas_lesson_idx on public.formulas(lesson_id);

create table public.glossary_terms (
  id                 uuid primary key default gen_random_uuid(),
  term_de            text not null,
  article            text check (article in ('der','die','das','none')),
  plural_de          text,
  term_en            text not null,
  definition_de      text,
  definition_en      text,
  ipa                text,
  related_lesson_ids jsonb not null default '[]'::jsonb,
  created_at         timestamptz not null default now()
);

create index glossary_term_de_trgm_idx on public.glossary_terms using gin (term_de gin_trgm_ops);
create index glossary_term_en_trgm_idx on public.glossary_terms using gin (term_en gin_trgm_ops);

----------------------------------------------------------------------
-- 4. EXERCISES — rich payload, no AI needed at runtime
----------------------------------------------------------------------
-- The `payload` jsonb holds everything the UI needs to render the
-- exercise, grade a submission, and show the feedback afterwards:
--
--   {
--     "hint_en": "...",                      -- one-line nudge
--     "solution_mdx": "...",                 -- full worked solution
--     "common_mistakes": [
--       { "wrong": "...", "why_en": "..." }, -- typical wrong answer + diagnosis
--       ...
--     ],
--     "discussion_mdx": "...",               -- variations, edge cases, connections
--
--     -- type-specific fields:
--     "correct": 42,          "unit": "kJ/kg",   "tolerance": 0.5,       -- numeric
--     "options": [ ... ],     "correct": "b",                            -- multiple_choice
--     "options": [ ... ],     "correct": ["a","c","d"],                  -- multi_select
--     "correct_latex": "...",                                            -- short_derivation
--     "steps": [ ... ],       "correct_order": ["s1","s2",...],          -- order_steps
--     "svgSrc": "...",        "hotspots": [ ... ]                        -- label_diagram
--   }

create table public.exercises (
  id            uuid primary key default gen_random_uuid(),
  lesson_id     uuid not null references public.lessons(id) on delete cascade,
  position      smallint not null,
  difficulty    text not null check (difficulty in ('easy','medium','klausur')),
  question_type text not null check (question_type in ('numeric','multiple_choice','multi_select','short_derivation','label_diagram','order_steps')),
  question_de   text not null,
  question_en   text,
  payload       jsonb not null,
  created_at    timestamptz not null default now()
);

create index exercises_lesson_idx on public.exercises(lesson_id, position);

----------------------------------------------------------------------
-- 5. PER-USER TABLES
----------------------------------------------------------------------

create table public.user_progress (
  user_id            uuid not null references auth.users(id) on delete cascade,
  lesson_id          uuid not null references public.lessons(id) on delete cascade,
  status             text not null default 'in_progress' check (status in ('not_started','in_progress','completed')),
  last_opened_at     timestamptz not null default now(),
  completed_at       timestamptz,
  time_spent_seconds integer not null default 0,
  primary key (user_id, lesson_id)
);

create table public.exercise_attempts (
  id                 uuid primary key default gen_random_uuid(),
  user_id            uuid not null references auth.users(id) on delete cascade,
  exercise_id        uuid not null references public.exercises(id) on delete cascade,
  submitted_answer   jsonb not null,
  correct            boolean not null,
  time_spent_seconds integer,
  saw_hint           boolean not null default false,
  saw_solution       boolean not null default false,
  created_at         timestamptz not null default now()
);

create index exercise_attempts_user_idx on public.exercise_attempts(user_id, created_at desc);

create table public.srs_cards (
  id               uuid primary key default gen_random_uuid(),
  user_id          uuid not null references auth.users(id) on delete cascade,
  source_type      text not null check (source_type in ('term','formula','exercise')),
  source_id        uuid not null,
  ease             numeric not null default 2.5,
  interval_days    integer not null default 0,
  due_at           timestamptz not null default now(),
  last_reviewed_at timestamptz,
  lapses           integer not null default 0,
  state            text not null default 'new' check (state in ('new','learning','review','relearning')),
  created_at       timestamptz not null default now(),
  unique (user_id, source_type, source_id)
);

create index srs_cards_due_idx on public.srs_cards(user_id, due_at);

create table public.study_plan (
  user_id        uuid not null references auth.users(id) on delete cascade,
  lesson_id      uuid not null references public.lessons(id) on delete cascade,
  scheduled_week date not null,                     -- Monday of the week
  completed      boolean not null default false,
  primary key (user_id, lesson_id)
);

create index study_plan_week_idx on public.study_plan(user_id, scheduled_week);

-- User-contributed notes per lesson — the "my own discussion" box that
-- replaces the AI chat. Renders as markdown, private to the user.
create table public.lesson_notes (
  user_id    uuid not null references auth.users(id) on delete cascade,
  lesson_id  uuid not null references public.lessons(id) on delete cascade,
  body_md    text,
  updated_at timestamptz not null default now(),
  primary key (user_id, lesson_id)
);

-- Shared Q&A: students can post a question on any lesson or exercise
-- and other students can answer. Moderation is minimal (report/hide).
-- This gives the "discussion" feel of the AI tutor without the cost.
create table public.discussions (
  id         uuid primary key default gen_random_uuid(),
  lesson_id  uuid references public.lessons(id) on delete cascade,
  exercise_id uuid references public.exercises(id) on delete cascade,
  author_id  uuid not null references auth.users(id) on delete cascade,
  parent_id  uuid references public.discussions(id) on delete cascade,
  body_md    text not null,
  hidden     boolean not null default false,
  created_at timestamptz not null default now(),
  constraint discussion_target check (
    (lesson_id is not null and exercise_id is null)
    or (lesson_id is null and exercise_id is not null)
  )
);

create index discussions_lesson_idx on public.discussions(lesson_id, created_at);
create index discussions_exercise_idx on public.discussions(exercise_id, created_at);

create table public.past_exams (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references auth.users(id) on delete cascade,
  module_id         uuid references public.modules(id) on delete set null,
  title             text not null,
  uploaded_pdf_path text,
  exam_date         date,
  created_at        timestamptz not null default now()
);

create table public.past_exam_questions (
  id            uuid primary key default gen_random_uuid(),
  past_exam_id  uuid not null references public.past_exams(id) on delete cascade,
  question_text text,
  lesson_id     uuid references public.lessons(id) on delete set null,
  solved        boolean not null default false,
  notes         text,
  position      smallint
);

----------------------------------------------------------------------
-- 6. updated_at triggers
----------------------------------------------------------------------

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

create trigger profiles_touch before update on public.profiles
  for each row execute function public.touch_updated_at();

create trigger lessons_touch before update on public.lessons
  for each row execute function public.touch_updated_at();

create trigger lesson_notes_touch before update on public.lesson_notes
  for each row execute function public.touch_updated_at();

----------------------------------------------------------------------
-- 7. Profile auto-creation on signup
----------------------------------------------------------------------

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', ''));
  return new;
end $$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

----------------------------------------------------------------------
-- 8. ROW-LEVEL SECURITY
----------------------------------------------------------------------

alter table public.profiles            enable row level security;
alter table public.tracks              enable row level security;
alter table public.modules             enable row level security;
alter table public.chapters            enable row level security;
alter table public.lessons             enable row level security;
alter table public.formulas            enable row level security;
alter table public.glossary_terms      enable row level security;
alter table public.exercises           enable row level security;
alter table public.user_progress       enable row level security;
alter table public.exercise_attempts   enable row level security;
alter table public.srs_cards           enable row level security;
alter table public.study_plan          enable row level security;
alter table public.lesson_notes        enable row level security;
alter table public.discussions         enable row level security;
alter table public.past_exams          enable row level security;
alter table public.past_exam_questions enable row level security;

-- Profiles: users manage their own row.
create policy "profiles_self_select" on public.profiles
  for select using (auth.uid() = id);
create policy "profiles_self_update" on public.profiles
  for update using (auth.uid() = id);

-- Content: any authenticated user can read.
create policy "tracks_read"    on public.tracks         for select using (auth.role() = 'authenticated');
create policy "modules_read"   on public.modules        for select using (auth.role() = 'authenticated');
create policy "chapters_read"  on public.chapters       for select using (auth.role() = 'authenticated');
create policy "lessons_read"   on public.lessons        for select using (auth.role() = 'authenticated');
create policy "formulas_read"  on public.formulas       for select using (auth.role() = 'authenticated');
create policy "glossary_read"  on public.glossary_terms for select using (auth.role() = 'authenticated');
create policy "exercises_read" on public.exercises      for select using (auth.role() = 'authenticated');

-- Per-user tables: strict ownership.
create policy "user_progress_own" on public.user_progress
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "exercise_attempts_own" on public.exercise_attempts
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "srs_cards_own" on public.srs_cards
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "study_plan_own" on public.study_plan
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "lesson_notes_own" on public.lesson_notes
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "past_exams_own" on public.past_exams
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "past_exam_questions_own" on public.past_exam_questions
  for all using (
    exists (select 1 from public.past_exams pe where pe.id = past_exam_id and pe.user_id = auth.uid())
  ) with check (
    exists (select 1 from public.past_exams pe where pe.id = past_exam_id and pe.user_id = auth.uid())
  );

-- Discussions: any authenticated user can read (unless hidden);
-- only the author can edit or delete their own post.
create policy "discussions_read" on public.discussions
  for select using (auth.role() = 'authenticated' and hidden = false);
create policy "discussions_insert" on public.discussions
  for insert with check (auth.uid() = author_id);
create policy "discussions_own_update" on public.discussions
  for update using (auth.uid() = author_id);
create policy "discussions_own_delete" on public.discussions
  for delete using (auth.uid() = author_id);

commit;
